### ISSUE TITLE
Dataset processing

### ISSUE THREAD

**Issue by MohSamNaf** [chongwar/gnn-eeg#2]
Hello.
Thank you for greats efforts and publishing this amazing work publicly, so others can benefit from.
I have read that the dataset used was a custom dataset. However, I would like to know more about its structure.

* Where did the .npy fiels come from? Were they already edf files converted to npy files?
* Could you proide a description of a sample of your dataset shape? And does  x:(N, T, C) mean N: Number of Samples. T: Time Series Samples, C: Channel Number?
* What is the purpose of  # (N, T, C) --> (N, T/4, C) regarding your dataset? Why did you specifically select the first quarter of T from each N?

Thank you for your time

**Comment by chongwar** [comment]
1. The .npy files were custom-collected EEG data from our experiments. You can create your .npy file from public or custom .edf file or other file formats for processing.
2. As with many other EEG processing procedures, the meanings of N, T, and C are exactly what you described. 
3. The purpose of # (N, T, C) --> (N, T/4, C) is for down-sampling to adapt the computing resource. The specific down-sampling rate is a variable that you can adjust based on the dimension of data you are dealing with and the computing resource you hold.
